"""Train and evaluate the PM2.5 forecasters. One command reproduces the results (plan §12):

    PYTHONPATH=. uv run python -m ml.train               # uses the cached feature table
    PYTHONPATH=. uv run python -m ml.train --refresh     # re-export features from Athena first

Per horizon (24/48/72h): walk-forward monthly CV of one global LightGBM model, scored with the
baselines on exactly the same rows; then a final model on all data. Everything is logged to
MLflow (SQLite tracking at data/ml/mlflow.db, artifacts in s3://<bucket>/mlflow/) and the
results table is written to docs/model_results.md.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import resource
import sys
import time

os.environ.setdefault("MLFLOW_DISABLE_AGENT_HINT", "1")

import lightgbm as lgb  # noqa: E402
import mlflow  # noqa: E402
import pandas as pd  # noqa: E402

from ingestion.settings import ROOT, Settings  # noqa: E402
from ml import baselines  # noqa: E402
from ml.cv import monthly_folds  # noqa: E402
from ml.data import load_features  # noqa: E402
from ml.evaluate import metrics, skill  # noqa: E402
from ml.features import (  # noqa: E402
    FEATURES,
    HORIZONS,
    TARGET,
    TARGET_TRANSFORMS,
    decode_target,
    encode_target,
    level_base,
    to_model_frame,
)

log = logging.getLogger("ml.train")

SEED = 42
PARAMS = {
    "objective": "regression_l1",  # optimise MAE directly; PM2.5 is heavy-tailed
    "n_estimators": 600,
    "learning_rate": 0.05,
    "num_leaves": 63,
    "min_child_samples": 100,
    "feature_fraction": 0.8,
    "bagging_fraction": 0.8,
    "bagging_freq": 1,
    "reg_lambda": 1.0,
    "random_state": SEED,
    "deterministic": True,
    "force_row_wise": True,
    "n_jobs": 4,
    "verbose": -1,
}
MODEL_DIR = ROOT / "data" / "ml" / "models"
RESULTS_MD = ROOT / "docs" / "model_results.md"
EXPERIMENT = "pm25-forecast"


def peak_rss_mb() -> float:
    rss = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    return rss / 1e6 if sys.platform == "darwin" else rss / 1e3  # bytes on macOS, KB on Linux


def fit(x: pd.DataFrame, y: pd.Series) -> lgb.LGBMRegressor:
    return lgb.LGBMRegressor(**PARAMS).fit(x, y)


def run_horizon(df: pd.DataFrame, horizon: int, transform: str) -> dict:
    d = df[df["horizon_h"] == horizon].reset_index(drop=True)
    x_all, y_all = to_model_frame(d), d[TARGET].astype("float64")
    base = level_base(d)
    y_fit = encode_target(y_all, base, transform)

    oof = pd.Series(index=d.index, dtype="float64")
    per_fold = []
    for fold in monthly_folds(d):
        model = fit(x_all.loc[fold.train_idx], y_fit.loc[fold.train_idx])
        oof.loc[fold.test_idx] = decode_target(
            model.predict(x_all.loc[fold.test_idx]), base.loc[fold.test_idx], transform
        )
        m = metrics(y_all.loc[fold.test_idx], oof.loc[fold.test_idx])
        persistence = baselines.predict(d.loc[fold.test_idx], "persistence")
        p = metrics(y_all.loc[fold.test_idx], persistence)
        per_fold.append(
            {
                "fold": fold.name,
                "train_rows": len(fold.train_idx),
                "mae": m["mae"],
                "persistence_mae": p["mae"],
                "n": m["n"],
            }
        )
        log.info(
            "h=%d fold %s: MAE %.2f vs persistence %.2f (train %d, test %d)",
            horizon,
            fold.name,
            m["mae"],
            p["mae"],
            len(fold.train_idx),
            m["n"],
        )

    scored = oof.notna()
    result = {"horizon": horizon, "model": metrics(y_all[scored], oof[scored]), "baselines": {}}
    for name in baselines.BASELINES:
        result["baselines"][name] = metrics(y_all[scored], baselines.predict(d[scored], name))
    result["skill"] = {
        name: skill(result["model"]["mae"], b["mae"]) for name, b in result["baselines"].items()
    }
    result["per_fold"] = per_fold

    final = fit(x_all, y_fit)
    result["final_model"] = final
    result["importance"] = pd.Series(
        final.booster_.feature_importance("gain"), index=FEATURES
    ).sort_values(ascending=False)
    keys = ["location_id", "issue_time_utc", "target_hour_start_utc"]
    result["oof"] = d.loc[scored, keys].assign(
        horizon_h=horizon, y_true=y_all[scored], y_pred=oof[scored]
    )
    return result


def write_markdown(
    results: list[dict], source: str, n_rows: int, peak_mb: float, transform: str
) -> None:
    lines = [
        "# PM2.5 forecast results",
        "",
        f"Generated by `python -m ml.train` from `{source}` ({n_rows:,} rows with a valid "
        f"target). Walk-forward monthly CV (expanding window, targets purged across the fold "
        f"boundary); metrics are pooled over all test months. Peak memory {peak_mb:,.0f} MB.",
        "",
        f"Target transform: `{transform}`.",
        "",
        "Category accuracy uses India AQI PM2.5 breakpoints on hourly values (indicative; the "
        "official category uses the 24h average).",
        "",
        "## Model vs baselines",
        "",
        "| Horizon | Predictor | MAE | RMSE | Bias | Category acc. | Skill vs it |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in results:
        h = r["horizon"]
        m = r["model"]
        lines.append(
            f"| {h}h | **LightGBM** | **{m['mae']:.2f}** | {m['rmse']:.2f} | "
            f"{m['bias']:+.2f} | {m['category_accuracy']:.1%} | — |"
        )
        for name, b in r["baselines"].items():
            lines.append(
                f"| {h}h | {name} | {b['mae']:.2f} | {b['rmse']:.2f} | {b['bias']:+.2f} "
                f"| {b['category_accuracy']:.1%} | {r['skill'][name]:+.1%} |"
            )
    lines += [
        "",
        "## MAE by test month",
        "",
        "| Month | " + " | ".join(f"{r['horizon']}h model / persistence" for r in results) + " |",
        "|---|" + "---|" * len(results),
    ]
    months = [f["fold"] for f in results[0]["per_fold"]]
    for i, month in enumerate(months):
        cells = [
            f"{r['per_fold'][i]['mae']:.1f} / {r['per_fold'][i]['persistence_mae']:.1f}"
            for r in results
        ]
        lines.append(f"| {month} | " + " | ".join(cells) + " |")
    lines += ["", "## Top features (24h model, gain)", ""]
    imp = results[0]["importance"]
    for name, gain in (imp / imp.sum()).head(12).items():
        lines.append(f"- `{name}`: {gain:.1%}")
    lines += [
        "",
        "## Notes",
        "",
        "- Leakage: features are built in dbt (`fct_features_hourly`) from data available "
        "at prediction time; `tests/assert_features_no_leakage.sql` checks every row's "
        "audit columns. Weather for the target hour is the forecast issued "
        "(h/24 + 1) days earlier.",
        "- CAMS forecast baseline: historical CAMS forecasts don't exist; `cams_lagged` is "
        "CAMS 12h before prediction time. The true CAMS-forecast baseline is scored from "
        "live-collected forecasts (from 2026-09-28).",
        "- One stubble/Diwali season (Oct–Nov 2025) is in the data; OpenAQ has no PM2.5 "
        "for these stations before Feb 2025.",
        "",
    ]
    RESULTS_MD.write_text("\n".join(lines))


RESULTS_JSON = MODEL_DIR / "results.json"


def write_results_json(
    results: list[dict], source: str, n_rows: int, transform: str, run_id: str
) -> None:
    """Machine-readable results; published with the model as public/model_card.json."""
    card = {
        "mlflow_run_id": run_id,
        "trained_rows": n_rows,
        "data_source": source,
        "target_transform": transform,
        "validation": "walk-forward monthly folds, expanding window, labels purged at boundary",
        "horizons": {
            str(r["horizon"]): {
                "model": r["model"],
                "baselines": r["baselines"],
                "skill": r["skill"],
                "per_month": r["per_fold"],
                "top_features": (r["importance"] / r["importance"].sum())
                .head(10)
                .round(4)
                .to_dict(),
            }
            for r in results
        },
    }
    RESULTS_JSON.write_text(json.dumps(card, indent=1, default=str))


def main() -> None:
    parser = argparse.ArgumentParser(description="Train PM2.5 forecasters (24/48/72h).")
    parser.add_argument("--refresh", action="store_true", help="re-export features from Athena")
    parser.add_argument(
        "--target",
        choices=TARGET_TRANSFORMS,
        default="absolute",
        help="absolute PM2.5 (default) or log-ratio to the recent 24h level (tried; not better)",
    )
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    started = time.monotonic()

    settings = Settings()
    if settings.aws_profile:
        os.environ["AWS_PROFILE"] = settings.aws_profile
    df = load_features(refresh=args.refresh, settings=settings)
    log.info("loaded %d rows, %d columns", len(df), df.shape[1])

    tracking_db = ROOT / "data" / "ml" / "mlflow.db"
    tracking_db.parent.mkdir(parents=True, exist_ok=True)
    mlflow.set_tracking_uri(f"sqlite:///{tracking_db}")
    if mlflow.get_experiment_by_name(EXPERIMENT) is None:
        mlflow.create_experiment(
            EXPERIMENT, artifact_location=f"s3://{settings.data_bucket}/mlflow/{EXPERIMENT}"
        )
    mlflow.set_experiment(EXPERIMENT)

    results = []
    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    with mlflow.start_run(run_name="lightgbm-walk-forward") as parent:
        mlflow.log_params(
            {
                **{k: v for k, v in PARAMS.items()},
                "features": len(FEATURES),
                "data_source": df.attrs.get("source", ""),
                "rows": len(df),
                "target_transform": args.target,
            }
        )
        for h in HORIZONS:
            with mlflow.start_run(run_name=f"h{h}", nested=True):
                r = run_horizon(df, h, args.target)
                results.append(r)
                mlflow.log_param("horizon_h", h)
                mlflow.log_metrics({f"model_{k}": v for k, v in r["model"].items() if k != "n"})
                for name, b in r["baselines"].items():
                    mlflow.log_metric(f"{name}_mae", b["mae"])
                    mlflow.log_metric(f"skill_vs_{name}", r["skill"][name])
                path = MODEL_DIR / f"lgbm_h{h}.txt"
                r["final_model"].booster_.save_model(str(path))
                meta = {
                    "horizon_h": h,
                    "target_transform": args.target,
                    "features": FEATURES,
                    # Latest label time seen in training: a fair promotion holdout starts after it.
                    "trained_until_utc": str(
                        (df["target_hour_start_utc"].max() + pd.Timedelta(hours=1)).isoformat()
                    ),
                }
                (MODEL_DIR / f"lgbm_h{h}.json").write_text(json.dumps(meta, indent=1))
                mlflow.log_artifact(str(path), artifact_path="model")
                imp_path = MODEL_DIR / f"importance_h{h}.json"
                imp_path.write_text(
                    json.dumps(
                        (r["importance"] / r["importance"].sum()).round(4).to_dict(), indent=1
                    )
                )
                mlflow.log_artifact(str(imp_path))
                log.info(
                    "h=%d MAE %.2f | persistence %.2f | skill %+.1f%%",
                    h,
                    r["model"]["mae"],
                    r["baselines"]["persistence"]["mae"],
                    100 * r["skill"]["persistence"],
                )
        pd.concat([r["oof"] for r in results]).to_parquet(ROOT / "data" / "ml" / "oof.parquet")
        peak = peak_rss_mb()
        mlflow.log_metric("peak_rss_mb", peak)
        write_markdown(results, df.attrs.get("source", ""), len(df), peak, args.target)
        write_results_json(
            results, df.attrs.get("source", ""), len(df), args.target, parent.info.run_id
        )
        mlflow.log_artifact(str(RESULTS_MD))
        log.info("MLflow run %s", parent.info.run_id)
    log.info(
        "done in %.1f min, peak memory %.0f MB -> %s",
        (time.monotonic() - started) / 60,
        peak,
        RESULTS_MD.relative_to(ROOT),
    )


if __name__ == "__main__":
    main()
