"""Discover Delhi NCR stations: land raw metadata in bronze, write config/stations.yaml.

    PYTHONPATH=. uv run python -m ingestion.openaq.discover            # bronze -> S3
    PYTHONPATH=. uv run python -m ingestion.openaq.discover --local    # bronze -> data/bronze

config/stations.yaml is regenerated on every run. config/zones.yaml is hand-reviewed, so it is
only written if missing; otherwise the proposal goes to config/zones.draft.yaml to diff against.
"""

from __future__ import annotations

import argparse
import logging
from collections import defaultdict
from dataclasses import asdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from ingestion.openaq.client import OpenAQClient
from ingestion.openaq.models import LatestReading, Location
from ingestion.openaq.stations import ZONE_NAMES, Station, is_candidate, select_stations
from ingestion.settings import CONFIG_DIR, ROOT, Settings
from ingestion.writers import LocalWriter, S3Writer, Writer

log = logging.getLogger(__name__)

CITY_ID = "delhi_ncr"


def load_city(city_id: str = CITY_ID, config_dir: Path = CONFIG_DIR) -> dict[str, Any]:
    cities = yaml.safe_load((config_dir / "cities.yaml").read_text())["cities"]
    return next(c for c in cities if c["id"] == city_id)


def run(
    client: OpenAQClient,
    writer: Writer,
    *,
    now: datetime,
    config_dir: Path = CONFIG_DIR,
    city_id: str = CITY_ID,
) -> list[Station]:
    city = load_city(city_id, config_dir)
    prefix = f"bronze/openaq/locations/dt={now:%Y-%m-%d}"

    fetched = client.locations(city["bbox"])
    writer.put_json(f"{prefix}/locations.json", fetched.raw_pages)
    locations: list[Location] = fetched.items

    latest: dict[int, list[LatestReading]] = {}
    latest_raw: dict[str, Any] = {}
    candidates = [loc for loc in locations if is_candidate(loc, now)]
    log.info("%d locations in bbox, %d candidates", len(locations), len(candidates))
    for loc in candidates:
        got = client.latest(loc.id)
        latest[loc.id] = got.items
        latest_raw[str(loc.id)] = got.raw_pages
    writer.put_json(f"{prefix}/latest.json", latest_raw)

    stations = select_stations(locations, latest, now)
    write_stations_yaml(stations, config_dir / "stations.yaml", city_id=city_id, now=now)
    zones_path = config_dir / "zones.yaml"
    target = zones_path if not zones_path.exists() else config_dir / "zones.draft.yaml"
    write_zones_yaml(stations, target, city_id=city_id, now=now)
    return stations


def write_stations_yaml(stations: list[Station], path: Path, *, city_id: str, now: datetime):
    rows = []
    for s in stations:
        row = asdict(s)
        for k in ("zone", "zone_reason"):
            row.pop(k)
        rows.append(row)
    header = (
        f"# Generated by `python -m ingestion.openaq.discover` at {now:%Y-%m-%dT%H:%M:%SZ}.\n"
        "# Do not hand-edit: rerun discovery. Zones live in zones.yaml.\n"
    )
    body = yaml.safe_dump(
        {"city_id": city_id, "stations": rows}, sort_keys=False, allow_unicode=True
    )
    path.write_text(header + body)


def write_zones_yaml(stations: list[Station], path: Path, *, city_id: str, now: datetime):
    """Hand-written YAML so each station id carries its name and the reason for its zone."""
    by_zone: dict[str, list[Station]] = defaultdict(list)
    for s in stations:
        by_zone[s.zone].append(s)

    lines = [
        f"# DRAFT generated by discovery at {now:%Y-%m-%dT%H:%M:%SZ}. Review by hand.",
        "# NCR cities are assigned by name keyword; Delhi by distance/bearing from Connaught",
        "# Place (<= 6 km = Central, else N/E/S/W quadrant). Co-located stations are listed",
        "# but excluded from zone medians via stations.yaml `colocated_with`.",
        f"city_id: {city_id}",
        "zones:",
    ]
    for zone_id in [z for z in ZONE_NAMES if z in by_zone]:
        lines += [f"  - id: {zone_id}", f"    name: {ZONE_NAMES[zone_id]}", "    stations:"]
        for s in sorted(by_zone[zone_id], key=lambda s: s.name):
            note = f"{s.name} ({s.zone_reason})"
            if s.colocated_with:
                note += f" [co-located with {s.colocated_with}]"
            lines.append(f"      - {s.location_id}  # {note}")
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--local", action="store_true", help="write bronze to data/ not S3")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    settings = Settings()
    writer: Writer = (
        LocalWriter(ROOT / "data")
        if args.local
        else S3Writer.from_profile(settings.data_bucket, settings.aws_profile, settings.aws_region)
    )
    with OpenAQClient(settings.openaq_api_key) as client:
        stations = run(client, writer, now=datetime.now(UTC))

    zones = sorted({s.zone for s in stations})
    colocated = [s.location_id for s in stations if s.colocated_with]
    log.info("%d stations across %d zones; co-located: %s", len(stations), len(zones), colocated)


if __name__ == "__main__":
    main()
